version: "3"

services:


  back-end:
    build: ./back-end
    entrypoint: .docker/entrypoint.sh   
    volumes:
        - ./back-end:/home/node/app    
    ports:
      - "3000:3000"

  front-end:
    build: ./front-end
    ports:
      - "3001:3000"
    volumes:
      - ./front-end:/home/node/app      
    depends_on: 
      - back-end     

     